### PR TITLE
[proposal] purchases-hybrid-common as submodule

### PR DESCRIPTION
**Pull request by aboedo**
This is a **proposal**: it changes the purchases-hybrid-common copy in cordova-plugin-purchases to a submodule. 

Pros: 
- Files aren't repeated, they're only references to the same file in another repo. 
- It makes it very easy to point to unreleased versions of purchases-hybrid-common: just go into the submodule and check out whichever version you want. 
- If you're developing `purchases-hybrid-common`, you can do the changes straight from the submodule and they'll be reflected. 
- reduces complexity by entirely removing related scripts

Cons: 
- This unnecessarily adds references to the android files in purchases-hybrid-common. They're not referenced in code, though, they're just a part of the repo. 
- It changes the way we track the version of the purchases-hybrid-common framework: instead of a file that hardcodes the version, it's managed through git submodules. It's somewhat harder to read, because you have to check the git pointer which will have an sha, instead of the version number.

### CODE REVIEW

**Comment by aboedo** [comment]
This could also be applied to the android and ios sdks. However, since they point to compiled frameworks, we'd have to add some code to generate the framework files.

**Comment by jeiting** [comment]
How does this affect downstream consumers? i.e. when these frameworks get released, will it complicate how people integrate?

**Comment by aboedo** [comment]
I thought there wouldn't be a problem, but apparently github [doesn't have the ability to include the files in the release tarball ](https://github.community/t5/How-to-use-Git-and-GitHub/Create-Release-that-contains-submodule/td-p/12073). 
this is kind of a deal-breaker, unless we move purchases-hybrid-common to a framework (which would mimic the way the purchases-ios sdk and android libraries are set up). 
if this was a framework, we'd just add it to version control like the others.

**Comment by aboedo** [comment]
closing in the meantime

**Pull request closed without merging**
