### PR TITLE
Release: 2.1.0

### PR DESCRIPTION
**Pull request by aboedo**
- iOS: 
    - Added a new method `setSimulatesAskToBuyInSandbox`, that allows developers to test deferred purchases easily.
- Bumped purchases-hybrid-common to 1.6.1 [Changelog here](https://github.com/RevenueCat/purchases-hybrid-common/releases/1.6.1)
- Bumped purchases-ios to 3.10.6 [Changelog here](https://github.com/RevenueCat/purchases-ios/releases/3.10.6)
- Bumped purchases-android to 4.0.4 [Changelog here](https://github.com/RevenueCat/purchases-hybrid-common/releases/4.0.4)
    https://github.com/RevenueCat/cordova-plugin-purchases/pull/76

### CODE REVIEW

**Comment by aboedo** [comment]
we should probably unversion the package.lock stuff, since it causes a ridiculously large diff. 
The actual diff is like 80 lines, you can see it here https://github.com/RevenueCat/cordova-plugin-purchases/pull/76/files/ef8e770a5a7350029f5cd3e851ec5f91630f9674

**Comment by aboedo** [comment]
tested on physical devices, both iOS and Android

**Comment by vegaro** [comment]
Agree with unversioning package-lock.json. Since what we have is an NPM package, I don't think it's that important we have it versioned. If it were an app, I would say we should keep it, but not for packages.

**Review by vegaro — APPROVED** [review]

**Comment by vegaro** [comment]
I was thinking about the `package-lock.json`. I was going to say it's useful to use as a way to know if CI caches are outdated, but I just looked and we actually use the `package.json` https://github.com/RevenueCat/cordova-plugin-purchases/blob/develop/.circleci/config.yml#L62

**Pull request merged**
