### PR TITLE
Release: 2.4.2

### PR DESCRIPTION
**Pull request by aboedo**
Added "type": "module" to solve #174

### CODE REVIEW

**Comment by vegaro** [comment]
@aboedo Do we close this in favor of 3.0.0?

**Comment by vegaro** [comment]
Oh actually, do we need this change?

**Comment by aboedo** [comment]
genuinely not sure. My understanding is that it wouldn't hurt since `commonjs` is the default

**Comment by aboedo** [comment]
I think this is worth doing, and possibly worth porting to v3 too

**Comment by tonidero** [comment]
Oh I don't know how I missed this. It can be closed yeah, thanks!

**Pull request closed without merging**
