### PR TITLE
Skip Installing iOS Dependencies on Windows

### PR DESCRIPTION
**Pull request by jeiting**

### CODE REVIEW

**Comment by jeiting** [comment]
Hey @phiferd!

Thanks for whipping up this fix. There are some other folks hitting this so we wanted to pull it up into master. Hope that's fine!

**Comment by phiferd** [comment]
Oh -- I didn't submit a pull request because I got pull into something else and didn't have a chance to test it out.  Which branch did you pull from?

**Comment by jeiting** [comment]
Ah ok! We don't have a windows machine handy so it's hard for us to test it out.

This pull is from your fork's master. 

We'll hold off on merging then. Thanks!

**Comment by phiferd** [comment]
Yeah, definitely don't use the version from master.

I started with the run-script-os plugin, which seemed to work ok, then I
thought I could simplify and avoid the dependency, but I ran into some
issue and I didn't have time to sort it, so I reverted back to
run-script-os on another branch. For some reason, there was an error on
install with that as well. That's where I left off.

I'll try to sort it out today. I'm going to try the paid version so I can
get postbacks setup.

Is it ok if the script is run after your plugin is installed?

**Comment by phiferd** [comment]
@jeiting , the current version of master should work ok.  The change was actually pretty simple once I figured out how cordova wants that to happen.

**Comment by phiferd** [comment]
You might want to just take a look at the changed files and copy/paste the changes over rather than inheriting all of my messy git history.

**Comment by jeiting** [comment]
Awesome. 

@vegaro can you take a look and squash and merge (gets rid of the git mess) if it's good to go?

**Pull request merged**
